---
- name: Prepare master nodes
  hosts: masternodes
  remote_user: kerim
  become: false        # DON'T SET ROOT RIGHTS OR SHARED DIRS WILL BE IN `/home/root/`
  vars:
    script_path: /home/kerim/config/master_node_setup.sh
  tasks:
    - name: Change `master_node_setup.sh` permissions
      ansible.builtin.file:
        path: "{{ script_path }}"
        mode: +x
    - name: Run 'master_node_setup.sh'
      ansible.builtin.script: "{{ script_path }}"